### ISSUE TITLE
List my messages?

### ISSUE THREAD

**Issue by Tomas-M** [whyrusleeping/zmsg#3]
Is there any way to list my own messages which I have sent to the other party?

**Comment by whyrusleeping** [comment]
Hey, sorry for the super delayed response (I can't keep up with my GH notifications).

It doesnt have a way to list sent messages, maybe the zcash API has a way to list sent messages? If so, we could add that pretty easily.

**Comment by Tomas-M** [comment]
I don't know and I don't care anymore, so this issue can be closed :)
